import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Toaster } from "sonner";
import Head from "next/head";
import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  display: 'swap',
  subsets: ["latin", "vietnamese"],
  weight: ['300', '400', '500', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <Head>
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <html lang="en">
      <body
        className={`${montserrat.className}`}
      >
        {children}
        <Toaster richColors position="top-center" />
      </body>
    </html>
    </>
  );
}
